sudo: required
language: generic
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
    - travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  matrix:
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=9
  global:
  - SA_NAME=hello-world
  - SA_PACKAGE_NAME=hello_world_robot
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - secure: wN10Zgx2qHC8iS4PMKEjNKvpToDOQ6YcjmPDgkjZBoQ1ZnPNCA9QW38J7YBUXTbx2ub/9bpCGvJCrxGxeGnyvtipCJxCITN92yTUP6HToE7QZGDNZ5uNjdS+BfNpgcFLVHcwTMtGWuyOENoe3d1kvG/edExZ4rZtqBAuVK3IpDt3iJTSsQSTk7kOB1Elzfn169Z766GkwUrQorByWI53484xOO/URxq0BURB6KuNW/QdyBnMcZs1WNlXQYgTZOWH1uEn5kYaIzz6X44hrX+GUSguQrlaiH3gy3TyYshghQr5a2qnTKQ4CSVcXCprBKJwlt1S1gTb2ISXlYcQGiTP0rHOMw4J3tTBIJA7y2PFDBJrcbuqu56QIdu3mnfsEk9u3PIWUTvm/ZeqqOSlOA5Si5nUR5AaAYyNuzIgqxfriHsbto70t+l0aYzZ76ExlgLjFu/q8LD6NYNT+h7Qgf7KjhXm55iUd5h68QMofjTRett+eYlGVYBrhKII0Q1VbHOiMA/+aHbzNNKP/h4A8atwudsD8VTldOgDtspU2nlRaT9Qnfwj1qrrNe2Gao6tH8c4at3sLueTPJYfQAJSkcS2Z1yoS1BGDhRoAxiB1Ou6OwuiNO75kwCG9FMXxviUUe80OchZtH/z2t9n2zgBcwX1wyZdxAgnf0Ox0Jz+O8lAaYQ=
  - secure: W3evZpeGXxTOAqQ6rSjAPA6EyhUnAgaAZNOXajBf2YUzyIxhscJn+rDurFWJ2P2jcNJnc1enaSPLHUCocwjoiMd9avO1q6m/KgsrN9x6vKB7BnWylxMp5f3GtDEbbVIfuZ7hR2p/P50XSy5Q1T0OsdBJ/me8HjkgYHtqKT2DlFwjtL2q+1sBVyT+uIYlgMF9yb4VqWtYK3GobG6j2zzw3m7KQ9fvIA5n0Abm7FjXvlocAkXBdhiyu+yvTO8g9vvTg1GZ3wMCoyahzKUXVXVP/WMaRSlAHQWPa/11pgZUK3hkUCxP4CrR6XjT+pdmdW5ZbscImaVqrMTiKnFC6h6xOPZTpl7Iztagd+9ey4RnzjsXKyBT0Bkyy4hI/jQQPnjNcJoeIxbkLXFYP6n1ptZk1dxSxLNzJNbsMw2dr9vtKThfTRxYvtbUwlzrW6031LbhTMEB3EjvJgr0eXxjxbRMpqD8s8345kjPvydk0o2PYCjtHR0vpLdJQ1SNJqLO31JJMMmQFbPCI/DWlTc97brhN2r8QpAxXteqrmucjl155oId9Ea+9/KwGPZYLUhJPAWHJVPYp4MC77Mt2qqvyn/Aks+i7ikYIbmjGldxz9uocmbHm7rantV/3uMS/xdvwLpm+TGUuTKslByxl87+yfxnDrhfg5/lPTG4ituESmPSJgM=
before_install:
- pip install --user awscli
- openssl aes-256-cbc -K $encrypted_e9b424f4a194_key -iv $encrypted_e9b424f4a194_iv
  -in github_deploy.pem.enc -out github_deploy.pem -d
install:
- git clone -b tim-dev https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- ". .ros_ci/add_tag.sh"
- ".ros_ci/ce_build.sh"
before_deploy:
- ". .ros_ci/before_deploy.sh"
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET_NAME"
  local_dir: shared
  skip_cleanup: true
  wait-until-deployed: true
  on:
    branch: tim-dev
  upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
- provider: script
  script: bash .ros_ci/codepipeline_deploy.sh
  on:
    branch: tim-dev
after_deploy:
- ".ros_ci/post_deploy.sh"
