sudo: required
language: generic
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-contributions@amazon.com
      - travis-build@platform-notifications.robomaker.aws.a2z.com
env:
  matrix:
    - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
  allow_failures:
    - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=9
  global:
    - SA_NAME=hello-world
    - SA_PACKAGE_NAME=hello_world_robot
    - NO_TEST=true
    - GH_USER_NAME="travis-ci"
    - GH_USER_EMAIL="travis@travis-ci.org"
    - AWS_DEFAULT_REGION=us-west-2
    - secure: "Ddxd7VrTOo6nM443+MYc5+NSeNUIZa9gkxPMoEExTBJD9jil9ulVI4aB51XRx2THaYUCah0oiQNeYBZAmvt4ECqT4KZ8FYwN1JykIsnPfIU4rHS099yxmBBvYRXzhr6iV0bcldFwZx6U4W4AIddjaLW2IlXmrPzzageSkSchdcFZfa6pxqQpE3w6eC16LCIVq5CDp93dUiRGtzFGNx/uaZjxlsFy/Jhq6xnsk/x38qT/tT+uVfUuTsz/ChhXbXz41k6U7OQi+EMjZ/LPOuuEulAhkpqXWYBsKi7dac0pb4rOpikCosN+8ZA1zuLEZKiVDdRvmbUorV2uHnomGEydTCft2cQkXeFkAM9wiVFrOcwYyBILnJQBiXpO75qmrvbVmOmFxCKnh58rk4PGfpnet42F9i/ob6P2O/XbmE0vtm7w6R462nk8HrvrJoTQGYrPeRIfotKL/p6hfqCHMRlqHivyRZpfmy8+UICJFtI3T+KzcRXBNMc40zGIUZwZeX2lYDxE195Uv5oKXZY2PEwm4hbuPcjHC8hu4R4DYS1NNX5ryyfhvX1DdiLVziJ0v5O2wrDXitZXfuyAP1BWBEpdAMMhSXZuRX6Uf2NAP20HMkApLz+nELeybEdsjsw896FRXLQpvNzgykZnIbFSCI2YI3ggymWPyPOLTcMm2kRjxq0="
    - secure: "k+jgq4Lup+qsTHhVyhhr9OhA2NqpiFHBbFVQBLaXxdUXOhf6pVYBPJCgIBIqPL6utAyUVX+yBIDNvUx/89T22RCKCZSvVMuOgQO41PxTECdKuA68KftHHN8xdBugR4K1rW+ywLalnmjz8p+I5xeaePbNEDmjnkIRiFjaaVVLPO3luxIcntN6BUKe8BzgJFimbbsRkAB2wDyQNqND6tfNoFDsjSEN4AIYhI/min/7TRgHZ04Orz265+c9K+QcrN2NgBjz2rADM9xCdSadGp94BOUflEXzfrQRA85Y/FnDMln4XD6ngi/jJ4Z4q3bKTJsAO9/gq9G0bhzUOrql/vLGV2XFs6EujZVs1GX4WOB7XqQOZYhGvpYhJ54N4tiH3+ZCZ8iFLM2f+ugasyJc5a5TEY8WoFfLAmAPpIHO3k5LeBx/lwwSaCddxPzCC1yPrmRl2nvY5+doCiL+4cjOS0Np6gaJXwS8YjJ2QFasVe7JAWGtl+BlDsL25Rp/GE3HQvBSikdAd9QX297L2wDhATaMWhWCg0KnaFEG7yLrgqNXXleGgCU33dh4BzcN3TMV+zqXEnsjiJsfeTbZxZ+i/07QLEFlgoJDqToD7rpkYEhoKpe5Qf1k3mQ/HITaUN7txykuJ3pjx5UmfIRyyGPz2nZ0zT1NsuP84oRfMZ2cNUbFadg="
before_install:
- pip install --user awscli
- openssl aes-256-cbc -K $encrypted_e9b424f4a194_key -iv $encrypted_e9b424f4a194_iv
  -in github_deploy.pem.enc -out github_deploy.pem -d
install:
- git clone -b development https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- ". .ros_ci/configure_cc_git_credentials.sh"
- ". .ros_ci/add_tag.sh"
- ".ros_ci/ce_build.sh"
before_deploy:
- ". .ros_ci/before_deploy.sh"
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET_NAME"
  local_dir: shared
  skip_cleanup: true
  wait-until-deployed: true
  upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
  on:
    branch: abby-dev
- provider: script
  script: bash .ros_ci/codepipeline_deploy.sh
  on:
    branch: abby-dev
after_deploy:
- ".ros_ci/post_deploy.sh"
